-- CreateEnum
CREATE TYPE "FoundOrLost" AS ENUM ('PERDIDO', 'ENCONTRADO');

-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "foundOrLost" "FoundOrLost" NOT NULL DEFAULT E'PERDIDO';
